---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude-agent-secrets
  namespace: claude-agent
spec:
  encryptedData:
    GITHUB_APP_ID: AgAi2uHiEsVYR5FQ5csBkuzsA/kAeXQBnhsYC80jxVAZ1Re0ItiQJ6kf3rOelBTtZftMNsaLPaXL9Qr7F27SMJmis/ZNHO3di8UdaOmJBDqcfOSS7aNfNLpp6g1Vv424o8uZyUNtAAor0M5s1Yj9ZqTAAXVVBa9tixwDSRFyWqvnN7Xhf/SmicxLtjHIPoA3ebqdxSowez1X48IuEFkCusVAf9yTNnOwwXbpJ0JrkYPbQOgMEhv1eIJB2tNPh5c4XrHMOn7oKJ2Nm3yj8JSeLb56FKmppXgYgGOI0hk6tYr7OhdcW1cYYJxWpTjACqcyeBmdu7mfkSrNTOLbPdu6gQ8ftuLGgYVWjhDf02MksWGQs3nfvNtIGy5+wUA4PeKttmT0GX/3T7LFR15JP02ATZWUoPNP1wb7Z/r3988Hnzbh+8nExMJSYMdjExUW9WjQ54s5wEGPBS/Wr5R/lC0D1rKj0SizTCSc8+cFatTN33eDplNtCt8jTDk5bxJAbObFoimwMc+9Lr/ElJnQG4PaKv0jYZZD1/j5EC+evxRsfGA+iH7kvvj6ltl/2JjNOCGBozoJkArG2UIwJgE0cbNzM3l4SAkR2IKy6eKJNMRyKP+McFsXxU2nov6n7UwOcf7nFpXgTN6smIJitA6m+cJtrKa1C7mJMDgAuXlKsqr6GILz8MpTW9RgCHdT03SI83rsni/VcgSkY4+6
    GITHUB_APP_INSTALLATION_ID: AgBpfl7gBzn5TuZ3GmNFAIUP2VVU8ZmiHQGArjL6zivrZ10lf3gTa4xwldBcEYPuxdqO7OVqKYZ47SQEFoXX5OzzjXPfUXfhqyP2INUYSRyi+y3XAh/s3DvzNk9gLjKLlz0TnElhUu18zfYwha0FJulBjMtcogdI6E6eJx+AYaxuXs+OM+0BLlLLwIveCU6PUkWmPlNpuz8eGDP1StIw1mj9b1UgCNoe0U7iu8d0iPWpLV0hgKXlXd/4KjVPycjeuqfDyrkxLp2quR2EBrHWhjsNeM/2hW2D2y2SspmkuvNhPNvWmLDSzBfM/BolSHoQKWjYVbKBO0m4dHsNFs1OiPaMPZfahxQeR9uSFWOvbfUhandzyQaUfH0JRK0lEapL2BYUVOWXkXl4T1Guqvx6revncAUXol1IKuIsHzYj/8hKDJeeOn30hJfgJ9g5917W/ROEmNEKcER3PpWw2tj3F8lAoVPnbCGRXEpJSQd9lNPS+eE750OWzTO9rQg/VTXi3z9l2NyE+D9ZU0M/B/PZK5pu5lYWYwa0i4Jky674oPleq8HojvEs35YrfWw/Jf8vPeLIL86nfBqxb4C3X5pgBWjU11PWcOisTIrcsUic+/5v+Z50BQfSc3xQgUSt3RDRNzkOFhJsuANSQutStkhwJPHpwG1vjJNWFDDCmkmxmuozuZv0e+56MtR9J3JvODQKKZlUgVBWX5X8cUI=
  template:
    metadata:
      name: claude-agent-secrets
      namespace: claude-agent
