---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude-agent-secrets
  namespace: claude-agent
spec:
  encryptedData:
    GITHUB_TOKEN: AgBv4s8OXgF6RgiHEjdSYbE3tgp3Lrr9+ZnFRNbTYSjDNUFNGPREfJW0qHKzxOes2XT6oM4WHhkprLXnNX1al84wQATIkhyJwcixYPBEpxVGYFir0SIvRI1RbuTqOTXeAGSTsSy/TG5up5ew3J0hmSUhIWH7OqXEEXGkjf2RT3U7WmDd8jINmWDQK/sX6mZvL22PyoLM6znX8WivbWxl1KRSRT5wK+9KynehDWUb+iPWznQF/sbP6CfOsYi1s6nIcMP0lDz4SKoMJY2TDhVc3Semqbd4saKzTSccAZqB72K42lNXgvMgvSksCcd2Bla1tF6kePKfmHq6XktUkxIXDGdJOf3r7XSrQHXJ5+MlLKl6X3RsHcYixoytwM4nKYeJc1YjdCRZeQKKL9fvGZJOPAfvHmuMu3ClCBaKL0kitcFCVg4/M3cB5+Jk0vte+/SnSNKQ4ccek8P6J7NXEtlrr8PLkVP9Ns3id2otbOCKwWJ3il7zAsiFUXWc1WNHl+psguk2ELiJsAz6JrcTIBpbRm5zUFc3OCEmwSBws+5jws3xJ1RkC6IqV+IVeeLuUcXfYxCUAsvVAagROZkmt3fY/v274fq/BvgiAZpQdis37IV2QTSPg3YLFFUIEdr85eHe+7FlmWmSaM/gmic/vUvVcGO9LG0Xjx6mFJvcrgJn2LOUCx3Y3xfSDFQmybbhB5u11pCb8Xr2vLM6DYcZ4tj4XmwI8uMuvT/d1SU9Rk59BtYMDo5xnOzYQjJoEsU7XPem7h5Zme5+MN2yPLA6lN7eO0I2HU5WY1MoA8YIaFz5ooC2niRzHXcBHzXSySqCfRY=
  template:
    metadata:
      name: claude-agent-secrets
      namespace: claude-agent
