---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude-agent-secrets
  namespace: claude-agent
spec:
  encryptedData:
    GITHUB_TOKEN: AgBdd/+mYKfYxCMH4wy57c7Yg/ijpOhqDhFguq598M5eC2SDPovEIFfgIqDQdcM86K7sTeNL2hGsznPTaIRxuhnU7OpnWsqhVf81b4PJ2exdmzN1n9RY6PPltitLvOw0SmoMZtaubt837FaMd3kCsC4KNcNikbIxnYwjBQTAOVaGTGpLt9ylbCnFqKqeelwRjclVnzIE5dKf+PE0QK2fLv9GAMo0LtRI56O8/FUrEFAwrDL+LusigYp9hlYuI0gvAsHhFFXaGIYT5ZuMISu0N89WLThWuSjFxBpqmJRGB4Hc2G7jiI+pHpbETb+Q2iZ3WPV7d0wyCNz1jWMk4bl8Rzurrywb/1FScQ+iPoggQSmN+Jlx+GDjuHDbo1G0naw7oQGKOvfNUZChsmLOcqay+IasxKmVIgspb9kn4HNikoY/z3MELTn+8wMLQIRRjVgtMSE8+xENSpTacr2C1TrJjjEKNRo7CNORhmNBt5EiHEp1jNmFwI5PoS1yJ0/LuzU0AhC7FYffh0Ufl57zvakPcNVt/63JMCrj53KW9wNz4EGi7ZdTslWpNj0RVwji2nRHgSRszEAd3TrJbMQeGCs5i548QCuoeRW2x8Mbpu3PFDH6qq2F/MGab3tNI03WXYF5MKQIWjc/cTbEsZMoQtqXLZEpenDyDklXOOX6+oWs6NCLL3FI3x+GW4IRzTkBEdBAusKRhn87Kr3LlnxnXjy1yC0iQuCjWE62u7u/w9z4+BaJGGXwPS12Jrnpg3g73iOIaiAtTE7jRxGSlRGtb5w+jfnL+zwZL9ybxoJ3UAJ9wrESy5DH5B+I2+dPI7oujh0=
  template:
    metadata:
      name: claude-agent-secrets
      namespace: claude-agent
