---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAj2hTlMWqOA1dticdGy7TdaKbGEvBkQ9rIE5b/0NiVTf47kfH6FtjFfpJrhcyFTix/DIMjto3pDs99iIsc2ooAnCfuRfuMdP+MvsxBHj/kcin4eTSQShipYqdcLJofYy3sPX+4JRXFjfbfb2akvmbUqxir+o7vfJFWNx0NNZ8pQH3QamrJwArcDhyvomcszyKtc0NlUwJiqbblMuMzyPVIb12GrV09jcboFju4MfTuFPoWwRXWpZduCesmyeAA/M106t1tNEAhvyo5QdGZRO/aPkb3lLShBBGi94AfmBcGxMIu2npeW+QLcMSA5nFCuEeUBJQb6sKgeaapFTLArYUFRHkuqPkqvrNunGJ/GEHwkWpGoKyWiq2M6r8DY6ljhW770v2hfuxDdhtLltdkE4bRZfpSnowaCovfEHby1gEvbJ66L2Dn14dg1UtqxhMHXWKjXV2hZi0dXddm2WMO5nVmle6EaXgrBdm5fWEnWbMMIzcyL98kB3gm5XEi7HG2hYsiUJjDO3dGlmvq8G2sESi6PTdltVVm8xE1ISNb53CcTCDS8tj38/wi5E8uLeQ/o+lZ25EUl1XeTM47DDfUDZ1DT6MnIAsJGZFjN4mtQlnQ7qvmUlLBml4ZnT9OgKC4xY9iqnx7CpxavG03vMy3gBDmBQAz7uLM8rh9CTW/L+Bll/UN+KRT0bs9EANl19Ox3xCAHZcmi+Fj5iK3WOcKGcwoMg==
    admin-user: AgAh81FKkTC0Cdc+bW5GEa6hOh43CHujMPq0Cuhq2bGihWiOAnVsCKwD0enbp20xbcj27Fl4Z2a5xXcMPbqxjHV8R6KE13dWdNooQufKr7iZ8x6Q7H3weNu/RpfTidTHqTG5ZP5NHlWx3wrwflKiJPAXKnbHBjz6G+hl7UD+3OXQy3rrkWyllwM0tZ7VF2ZAQ6tigohwTyW8Vb8hXwWQqD5KPlCeYKzigatOzHVpdlOBHVTu2TojpaEnsH8eofdz4w+HymC33cBEZamdgZfNfyGVALRIPVTg68nqV3a2tb6r3n6JDh4Jq0CBVpak8Vk5usYoBy9mDxQTewuBaGUHjL3LtG4E/HBKkER691x4EFBF5UUq/6u6aH1ge7j6V+LwrXXjPaOftvjysdZNUPTs/SH83e/w1pzL4dCiyp8ZNKVQmfTmvkVElKmVGM7ZNPwU64FGqPPDqkMthmJL0UL/oOSnVRtZCaNeVQad40/55bfFxoD62BK88q3WdEjeuv0FkfaZKqMjVqUKAcJsBPrOg4md+9ejstr6G4GF2q4GzjGja3ww/eKhQBW0niYNDwRcznPPD+4/PcEUCrDxANTVNwFQC0sW8S4+uhidHZU62BkZ56qIl1FWpaPFgyTnAjrmj3APddP3MxfMQwBioTklVDoufStxU63E9AMlMIbqWAs8opMhuPX33tzXbnjxBB8gmTej+8rLrA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
