---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: agent-api
spec:
  encryptedData:
    .dockerconfigjson: AgCPh+OqMbDUOdwxtdPLJGTXmySIXfXAzJETm0yNsu4eO+KWPV7CrPwEQhwU9VpRZx0LlJarFZ9P1EwRwjeRvtalyX0AJQXuOU9jXuT86+ag7EYqaM7I33U/PZompT1gkKioU3ksPx/EDNG3qjIaUAsEheFIMqdATKxKoTBBdrsm8bv0pwBw6Oh+DBraAfMrJJ2iW/i0ALMb5en0MnZyeSphzstDWjUITUwqcdKsylfivn8CIG/xwTmQI6YxZBjKAwKyuJhXv6YUG3M6TOCGXRFVNZLgIr+VMpqmlKmn4eXd1BBGmAwfFsyf/kf7ow4XVVrCSdxJIPn3R1G5WXNuOjsloPDDqw/rABS/msRVHOALJzLURr4FoDzzL0uDNKhW4TSJ642auRs+zHBM/M6oDXx9LffxbFpRfHXVbYjCiVxjVoxn4vYUBdhrYG7lO2eccZA8DAActXe4dP17bvllbeXJ2YxdgzaHYVV9OeTkXRlL4pqbfSyzFFP+EedEnGt3siwBuSXjIxgOJKZU4xkb3c+4Kn8PwWc8hdS9SHOX4DsWdWkOKcqoD9dwSf6ASwOP2OMuIHrnNYJewMvXk/nhdbcEvhXO7mug0Rr8jRS+PBBb0Fs/NnNjSPEmFcbKE5Cj7tVUwbsfU1AxDUOToQ9RJAvQjQggxET23YgUnZ4wrax96MBaMsdkyvIo/Y2ZJYBS7JT/GmDj6pDH6LZEaeCmjloCoXhp/yGY97xWfHpZubQlTpUoa+x+hKZhNh6I2Jhj82bI3+DH/kGKgRYW2rCBFWRLg13aCBZ0iFSHXXNynKsWaoIJ2CDNBLrK8ig1gxeRlxS/Ty1rPknyIlDmyTRCqXxq6EZPMtYsF061f8RPZsfW0kDlbuNn/ac+dNbVbdUXHceOJdmGD5w0ECsbROAhFgWKJW2OVIz/k3pxZIPymPw2jDw=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: agent-api
    type: kubernetes.io/dockerconfigjson
