---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-api-secrets
  namespace: agent-api
spec:
  encryptedData:
    github-app-id: AgCXp+MiZM7dWP43rvpz0vTvNUmsbXWtiUXFa2QhfVyejAXBitn2jR6FLmTj0DbA0lT7M3SK7zw2dvllIEbxLAW4SaHwTetdWzgT0yJWuHp3CTAHWF8DeLOCERXNWFLQQZoPEXoE6dozJXrE+AmmJGP8FHb/ys5gCZOsCr7CEJLIo1esldeNrbyBPnKzR3gLoxFt5WuFajEOKRoNuusRVoxTm4JX0NvXcaT2AM+rb9c8yV9rpyvISleorxw4SczOGi2qjb4ueEiYZ32PtDQpNwcOiUqHC8bg62i2YJP9947cdv1YKJtDOVv9bv7GoP39Ce8464ONxoALzV4UopYZjPOS8betU6MTM/PCNgc3JhpGr1B9JiW1i/03l/GIxmg9fcUB5YDVMQsNZAX/28LlxhpLfIOEmiPwwuoWW3xdLbBanO3FyrGggHnn9Hbw0eJ4hfOy1MqA5GnV/MOIS5FOuI2bHoOCsKn/xnHGMkCg5BwAg8JMo3KEgRfi5BJCr9ehKSBRIpknaKIkvg4e3COBsvdi62YLoToYK6lhdMELusrMP4Q7v021QyJrLwRw7vPuSZ7arNQEug4+tDE+51benkYHeEAOQtjVhzMSbtZ7CqFwOPx2WTRtQz/2F3w+CCE1uiAaO0kVc26SnmjwkqjKY2tH5plX+Otw99rTMaH8Ag6Ebk3/TXqtgTD1lvc0KqoDCXN6zgO2W8nk
    github-app-installation-id: AgB65cmK7rlBUA/crXM9rjcJgjOTF0CnE8FUYEGuGj4R1RAfvrAcNOANugfysVwne6NldaaD0h4MJuf0LYHgoTdHKv1tfFPWAySbaandwtYP+ddnPXfB+tvp73GR2ZQ7avmq1/X2AfxzMpimNS4NK0YWzaHI6qD6hWUtUT6ImDw0aCI+t3+d1oYDtD0yePhaoCRJtMRhtpQatfgP8gmZBN423Hd5udZoIYD6/J8AiVFO1703zL0AMb/OpZhwYCAQclkgLkWoj3/wSc8fozW4kAnkrbKNJK+LFBnLpp/TVZh8g52ckJHz0wjSl+wMaaOO6AM2ZJtl6yUXplumcadiDaaO2pHiNm6VER3+bbi8MKJ1y5a9PnId3hxKZhmnEnKWTSOA1+9sfu5Is6MB20uTkZ/5y0A+brvvqbPJYwLIKGX6lWBSUKBUCH+F5NgZtnkqS39jN6qJmeQ9iuKNet1YOOXlpS78P6Z4aRUNyxR6giOu5mgl6qwqJ3SdS2Mry+aOgnQSQJAig2LfexPtIO2fxGxsMBf+zb38H68ET3gpnnRa7Ru0XiYGBoCXOKq4JulpRYyGulPGPoPXtiQGZ7lvtUheGfYP8XMyaG255uPflfHDAso56sSX5VdQ9XEW72WloTltzcQt7XTFlygq5NMrtiNY0yFNSiWM+aUDTaOttuuF1Asf1BHH9+mtsWxdan4nffR7hVNd39zBH6M=
  template:
    metadata:
      name: agent-api-secrets
      namespace: agent-api
