apiVersion: v1
kind: Service
metadata:
  name: chromium-browserless
  labels:
    app: chromium-browserless
spec:
  type: ClusterIP
  selector:
    app: chromium-browserless
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
