---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-pg-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgCT7A9iX+0uirL5R5ADosk0LLDhHFEWIJ0XfmMbt+ev5QxHnI6mU/n9UPQtbG1kn5aHEdJMxJfjNfGsuak6TRJimy97nlVPNXk3aVvaCQ4mOtuCd4CC5FNN6gy/0I4qIvSR/bEYwQkgO9D349Mgi1Zx2RaL0fYbJVfT3j2xj6lxRamXdFbSeFANRTZSQ4qSKMWixaGyJYwHxcmFc5f+0uoLQ4Fra3GmJW3QAhR8CVES93NTpPhjPeJS5Jp4nDZOHvJ2XW7HttjNZ656xHOoX/Ua6Uzg3pZvYuaPbRs4pi23+zgZ7K5WmWigZr0ni0cSLN2ylo1feaWpoyqHdwGjlfrpw7Of/REx0Rkg25Me03ObKIU5oumuFoVHp93HSs/+By82vhpMBrZ6LAp0xDfIUu7wTfaEyoe0fhNKP08mzbQO3pSNXRq+4NLeiU3zoOuEd07jI05EdLB8l2TwORDxeQj01AiBD7tCNctzJR95MSABhrYKf4//31OZIrmzHtEbleiu4O9b7kwEwdrKLbhs1yqvxwpxX/WMSd1609Eqt2BaQEGcjylKcWV8mDmEh6ccCVuNGccekZzGOxHewcDj/HslzJc7pzM3Lu2pwhFCua0ST9Zmk36wdzNV+qcLv4/R8ueFMAyRIxjRGQWh66EG5kf2rBeu7ORsO4s58LN0qWR8JtWYNVb5JLVFOQHX8XIgWQnoneVcgOUY9DwgEzWmw/4lRYClUlvYORxabwevMdBaxw0JvFW7te25jvq6+L2SSuI4rilBJhSsb8J+8bjwWbfIVHNi0xo9AsOZcEf4TmAMvQ==
  template:
    metadata:
      name: authentik-pg-credentials
      namespace: authentik
