---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    secret-key: AgCZTUoOufBodkylFleVPVnO3oEqSBaiRBcHGp8YWpI9Bs5lndx1eWiRiv8Xh+p6+RS+vCu24aRqBHULcbwJSjJJLtMDBJTfrqRZqkA+ADiKCorA8OWvud9sU7xbQa1kIHuLz5qi6Nl+F0YvcStb58Hr9+aBN8m+UMkVq4Ocx7gc/f2n+1/YN0DhE1UxHSMCxrjJGxbbez2BFB15d6Xnub73TFkp1+CyOR+nJHtwzZ2ASBQsNxw7G71Lasp9xO7dUSFtXVDHsX1i76n/pPfsiLi3IuuIn+Bzd72HC8lQSpGqRtuUwgKAb5I5YGeio9TJgVe+Hu4uRl31JzL97h9pLoVdC1qoMU7dwVBIen3rPxr7e9XeQXO4IlV+nMrloCHITHfyEBfxFjNpJi/mpTE+MFNHUkvqLcog7lUBuKhVAA7ZdTYws9UXXPTNLPJBkZZG+PHwf54YAxMHcPu/WlJNYPNFa+ZV8U3G3hf9iI5jca+6EnWSS7JfupQHBKcB1KkdwsFwgMwEpjLFW5Thc+VrR5RbzviA+3Y2cuTo/sYByRDry4TsgQGAPaepkvlQEZg3sJ0p51Und3xyMd6tJlzti+/qTBBqUUcP/rCH2xuJb7QmsL9R1oBpZfbY11kv1HGZb5jpBrKNLjIilZKzoLgMHsaUtWTwdWqnDR0pO5XRAxynkcFl1q159sVhYBQ8N0Mr2ogOEevsDnSJgfRWaZRDL0TQG5qxq1WRbfUpYzDPmcOOw85rclE/B45QBymYkD0m/q6qCTO9LuOWe3e3aslRtuuHMkGk8ctPXordJm0EpkQxmQ==
  template:
    metadata:
      name: authentik-secret-key
      namespace: authentik
