apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-rpi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: raspberrypi
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.16.1
      helm:
        releaseName: metallb
        valueFiles:
          - $values/apps/metallb/rpi/values.yaml

    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      ref: values

    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      path: apps/metallb/rpi/manifests

  destination:
    server: https://10.0.4.11:6443
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
