---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-pg-app
  namespace: postgres
spec:
  encryptedData:
    password: AgBeQq1CGGkSgDP3kGbUvbmCsRcWBy67LlHg9Odve3xAissmcei6O/F2P72IK7Qz5u7jPn4Xv+RgnUR0xw/nananCMiUQ1yjY92Ow8ZYq0waXnOGp/miAALKnuawRyIVl+sI3Pxs98lnEbSb2qjR+7L5EpcVEKrKw5Gq+5U2mLzzpjjf4usGb0HbaABaODDcBLDurMEsS6s/BrFAB5ypspWoyys763WC6cAkBtZInMio2qaKv1ojLyLdVw04SUgmDtGiRftFIdbpVJZVsCRglihGYA1EyOZyfi9DKG40/Di8CAmnJkDCXO30q0ZMB+I7/2If15pspw7cfcFuBVyfDOdMHlR+cczaxkCEq2h0i++SM5mL8xxm00Vcn5RfqNdmw9XEzWT+Xa326Jv7ho5l8CxccEfsjE2ovE6FLx4QSqUNuQ5ERRSXb3ubhvIDF/2NBQYqJYuU7BIaU+j4hHnb9AY6jCI8xvWHjfbKAKh0PigAZwxkBuFIv3ZQK7yTqm/6crIX3BV8MciALSbA/BSGReJC6hG5C2JrWnewiG3RgHngE3tGsO+XrLH+Htx1D/WXFM8fyUkgcsPXH1hOZ75K112NRDe7eyUaAF/IlBw+cHA+jwNgaboaiNWu1c5fpefg6b12dMtCWXGQgaZGtsDY/Wy7DinyY6PPGjLB7b+gktSFPLqd4L26yT1uYqC9L4yVXg8EW9dItKKuCv0+2dzqKTPlJs+SD08bBu7RCXxeQk40z+iUG43oPdBbtERveMG8DQ8Msh67YIiyk8ziRQOWzavYrGUGo28qwuSf7wBN6mcfeA==
    username: AgA8vzIBOsDwhEgnk51Um0nncGivQ8At5Kk6sQsKqQ+S1kwq4r+55tX7KmRwqOVLTlZj9FdneWm4cJ78ocfYxcRBWfWm2uAOJazuu4sv0qRvBEDqvHESYY5VQqOYBcUUiRYoyUAx+Zgcw25IL863Cvjz1YcMQOXRSXaHswku7pZ0T6Fec4bvmeYeA8e3R6v9gwXfwEtgKYXwsFE8eydN05Au3MpXAtu6Zx5alW/B7+OJLvBnZI3y7HC15tWBaFkpALeM3exdXj5JPLir/tnS2qL8IzxGp6nxy6MzMxiSM4K/pruEoJYPdlQv3VVmWuB9GBRz4tTkyHkewFQNbOPVPTrwtqyJvs8LsXn8qt5qI/2oSUpmLHJ4hdsEp/twu+Uf7nlowWpfWfJOJNva426vnE6/fG8BKj03/DPsfIXx7piO+eM4DHFhKjErBNTGemRl+mrZyPDbVPi13avH5xfiwBvSkNpySBR6KT8T9C3L/uVsIzjxlrP2RKj99PCd1yH/rTKmx7o8NDXjJn9LprwaojdZHsW3tLooiXr11rIFJfvsPYiZDXMIg/3L3d34HSreQmD+u3xDYMQOvP56lXYAWaEkHVCU2MbxTyX+xzJP/eXs783lMl5nRHmbOmJaxu51cmiUdP672tTWwG9G7W+Zdf+hLDyq8Xubigo+JfdLw4YUL2eEUw9s/eoBUNFNKd56tQi+OVJgTUM89Ms=
  template:
    metadata:
      name: authentik-pg-app
      namespace: postgres
    type: kubernetes.io/basic-auth
