---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-superuser
  namespace: postgres
spec:
  encryptedData:
    password: AgBfvPJrbheWF5KQcRTd3028taVagEQkkjRZOV06BeYLeUNlNwM225YEYopxsT6L1PgQmJuN84qytgPbuj+KnlFOBJINe7H+J5qA/fnHT7CZ6UBLzmJlUkrLQh5hwGPoBHUBatEdUHFoL94q6ZyuXLcjV5isOZjaaJ/GaGw6tYBU7+gIe6AU05DiGMnEzDkJ3+8cuuuww937MKsSSd9+GXHjer3CN6vWmnhA3tnj+othlnFYLvoQsCUoD4LXQqi9gWFq5U7PqDpKz1PXuoAhbLT0VeCofdqD+Bk7hsp3aqfcp+xUk84AitZ0aNky6B4Hu8cO22j7RFr/Oe8238YiXkmnwbAijD9/ZQju+XhjQUUrrktwGfUlUYZnFyh/KyK/xghLBktyJIFuxpkhTI4C6fnrKHZDk5GXvRR/dT8fto/EdUIxl5CQZvFYLaJ+glpq0CNxtBgmNgUmDWjZ/1fO4TpphHh/dBNIjWunY2zLJmghsMAnTeK9ALeWkC9hU/v9MAZLjoGnE5ja5e/iITrerZK2FIylaU3/Ds2UC9iYNLyJIEW0lTnAGkiHNv9TBTKlR58C3eofCzSzUofQ7MyhbvIGFgIdy5331R6bX8Y5fakThP8vsb6K4xPMH5MxdQh6kK0+SDkF/poI2vsRSTZGLRCTcU288eBxIvVqiJL5TLz1ICg9BZ37KGHHX11kl1gsE7vX1qDjL4akA2+FcI+aFnx4XrDryaRnecoy3/ke1nvEP5Kbm5nMCqCHOF4ty+Ss35857RVBPw3sL9KksXqoLCfzEsgmJEFvk6mBBgwXR+QXIw==
    username: AgCsXhgISWw2HdkTAeFyvVU0II4yoiLrN+EBpgRyLdc40Vqq4FCc4Vb/Wybe6guWwDy6jTopV2L/mjrpzTaMxiLLijxTUF51NaXEDvQEQ2jvEvkcXZ8d85FnDjafMHbyIzLApCeCyrmrIEERVpJlUvhBJyxdzmU1qAkuc3EuHvCHx5tkX8NliMATPMQAyVPA62wyJQnOlZytiQRfk8oB08rQXYcGU6FSeYi/Q46S6sgagK9nGr+V84xB0fsNBeSaRsGnr7wiYXkyydemYcnZP2dh4tcfWVllUTSe8MJS7b1/7OtgFskaEK2mzLq39QTejDaLuFctu86gZT/LyCNrogQp31UsB0yJZwJRvOOTUoEwSkflNogu3zyysMY956c+nqoRYHXYvdgocF105MUDkeAtbJ+gD+lfKfA9B52ZCCehjGp+oDFkUPIRawA015FohpzBoVUDr2UFSL1Z3sOoSEACqt9ISUGHjyOQ4Gi1xqEc/Wv04cIE2na4p8auy42vhTlZskFeybl3pTwo8waoSaYIgZoFuanAjzdf9NmMjapo3NuOBsXGwBUxFpJOMcbs1BXmUKYe03SdrYPFpifBa9SnyTidXGHhcPaA5drG2HGuC+zh7xT7YMJjQOIsmzbNFKhAw4/+NdR4qcZMWgihLBQtPIFMBzTqii51Bl+LELjrVX1bW6r8a9EgqhOoSwMrL8lUk0hEU+0tNw==
  template:
    metadata:
      name: pg-superuser
      namespace: postgres
    type: kubernetes.io/basic-auth
