---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgCLIcXwbZ3F+sam9JkLwrzktRHmctX+vjx/4Y7qtZ1yf144Xg6Raz7+6rS6Mr3SrWM7UyXI8oOT7e986DqlhfAZMmk7kxKqMCtzbxMPk1gpzBtf7ztzLFjtmjbWcqvlK99GqCzij9I0HzerG6mUTEcOTZArtpc6oL+v2nfT/oAOJdFSe7jh8CNBTfu0Q9IqKfEZBEOhvuGWnGVQ8fN/orww8O36Hax+Giyq0G4NLbe/aXMVvW6Y/syXKGxpnH+v1LXqACHxWZAdh0dcHc+8qa0Iw+C5W45Z+xUI3PZrYGaMeYIMuUC0nIovxqBmdQt2MhzNAyvnVeSA5dS+L6NWvTYiA1eFmRYms0q6zJgXi4FjTjOaOk1+dW/OX+VxIWWKD9l8dkh3M1aRe7WPLV4RGphudy/2TocelhjvOGDE5BzEX40EFYYJdwPpa1eOlREMS8NRvj8QUlpRd59VnhRuhpQatVrd2iGZTT+jpVvDXXKeTFChR8fn+D7903+V2dQ2Miom91TzDpEGYvHL225AKru8OWo2bmr1gl7wpj3Ge1LWIqisOWJUpqi/IN4hUqJ+Y3S631Qmz6XHbTqFPWnj/IkUgN/mHnGdRnSiUGNBigXrTZbZVIobC2p9rSs8uO1Dc/JuRvMOY8x9FS03S2F0TnzPVLrp42XkCp2Z1AUZVH5l1EPJIt1iZpfRgBctqOaQTwEJkWE69YIxYcXTxeq7CadpSO1nCdZ6ugJmgBed24AMUiFiC7nbGnBp11VyvZ4IXZ0Vn5bKhY6eqKraPkl1bdhG
  template:
    metadata:
      name: openclaw-secrets
      namespace: openclaw
