apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-rpi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: raspberrypi
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.18.4
  destination:
    server: https://10.0.4.11:6443
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
