apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki-stack
      targetRevision: 2.10.3
      helm:
        valueFiles:
          - $values/apps/monitoring/loki/values.yaml

    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      ref: values

    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      path: apps/monitoring/loki/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
