---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-mariadb-secret
  namespace: wordpress
spec:
  encryptedData:
    mariadb-password: AgB1gC99Zfeu7K+Bsm7MjARiC1y6ZVrrPYUhH0/Eqb8TLhB3vsO06SlKncrEPGj4hCddabJqvraoF3LYxfAXvK1ZQEKcFHlo5iwtaUUZhBx4VvIqtrbO04ualmUkd3kRnYxwxcCBGVYmjbO2aRzUqzc0EKXH3zfDTK1b9wZR4FQ0dqFI7oT19aoJ3LR3n3rKVv3jbQMwoviscKIbvH0baZyG7MgHklqhcyJo8knSGDuhJbLLuM7r0QQ4KTrfGcAAophTdun2T9uAeTeT5ldHD/1KCrEW7jII52JMi3mnFk0e5uYyxRTkOmzkN8zNo1KhLAYd7p9BmhpHYFV0m/0Er20CGDl0n/g+zUzy/qKul7wCYjULVdtrNu5LHS4oNV6qWh3ElpJulEGz0d2O7mhyvbQoAxxX+tZB6cAVoCUgvdUW08AkwgNiNAEUZ+HYI5oW5YuJTiIfuTQaqxn7lvipMd8zJ/10Hcbe61CitagEs+L8H2T9fcDKjv6csfWeD1FwOBq09DBmcLUOm/pXyjp2Jw4+Jz/tjq1V5Ez+LQZlsSsyJ/JiPy9yepUcwNBtpLw4OFAbRPL1tngSBDOr2L1jG4KeIhQ44DtT5VWzjTUQFeGN9WaaMs4Ppx1IYvvA/4P0ukt2ZFkxnzHvNFuFShMWJWcPQA9V385M4QMeA9bpXT5RV47451MIUU10jmycCclec/Akxc9oD5SjkAbk5RGYTHn1+s0wqw==
    mariadb-root-password: AgBkj89G6XY3PigO0ZgUfPjoPVf7v1BJzaJ4KdnRq9F3mna/vSFpZlaLunkJPO7VZH9caWjo331SEn3uAc8MMkE2IIeQWY3FcayFbFfw7cn+TDIzzpVlMYfCqNPH/JlrfiKGjppTWvK8QHmQH/RU/M5J+N5jUpvPXVQ5at2/llSXAYAvEijKeje+1qkk166dG+avscngXNJ6/DSkJWleTihn2IpzN8Vnk6FXN4t42fcCRFL3qfK3ebYFsN+T5kw3f7Cb3gcrfsbVUQwejzU2PmUQkSma37EC1bfAVbaztEd1KT/TghMt++CIxSIBZ+F+0aAQXfmDgu02AoI4phylvaZaQp3hKsbwvlpr1pOeB66yKU+yW+UddzYdxIAgwR9bLWVtBRDFplFmKGDMMm2OPbuP4QXIutLeaC0osa6XqGtTuba6KTQvOkDvoiVOnA4h/6vEy2oVbslm2Za6LvLlsjJhIAgMSw8Yb8EPWXr9ekuoNE8N8ls+hOudZLM3pRl1NfCiv26Ad5CnzXNRJoHDRdMg8VYzDdq+/RuHgeUnZs+Q9SnzOZ8qOHkZsyj99F5sKPBpp5SWPL26DXyUwrBM/5uBL81dQ2xqMVfx+bS0RY2j0xJhumrNuHuQ+gEwIyC/I9GsRCB5cFGmoR06PXjDrXcjpew8y7PmX/WQA0dgYUTCbog10Dc71on4KqWKv8yfpXN40wXcwZviX/OcEHoQW5xPfSkfIA==
  template:
    metadata:
      name: wordpress-mariadb-secret
      namespace: wordpress
