---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-password
  namespace: pihole
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    password: AgAtHFKYFXPY6bm7BVpc6rsanSTdEX2nEsGtzxIKjDEtsuaV4wtkqO+Q/HDKoOwSBc5R5DgMI6VUdS1Uqw7wgrTdGaw8IgyH5lHUM19Boz9tFxudwPa+SAbB7SIy4yONxUZvqfXjNUB085fZXlTSR8TEGQi5BWmc4my+4oy+nzgzzIL2LIYhiagb3kvcA/vCHjwQ2ApvSSn+O82av40h6BBZSgBGTBzcy2rWmFvY2OMSdpL0+QaVPJ+/zRWsFUzX8DMPkNOoznTuNBsbd1MQp1i7hHquPCHPtttF0PdvnL8p8xfUQSUh1pmb23naxA57EwICxk2LPdp+2tnSjF5/4NGx+VN13mx5JR7iq21xPJKou1ewVk5pi8J50XXbMQZJv38DEgjCGmI/QbelV3y0bsC6Y7P621vDzP14dpXJr5EM/G3nzgMidzlGfbzpsjivSR4HIRkCQJ4unlrLjla/CzC5QVjbKfg4mUCMlfzhuXgQsATcnZixDVfmj4c5+/PStMzkmgdNe5Y/6GDOQBltUfn591+aq4RnRm4ypG8UE2hAbqjbOjmu94P9rqumPuA6dRPfVbZkIHJ7/EaJCv/v0uWoGPODxRtKYpH8pm4k6+HOcrbfXiB42pcdP9wEFGaOD0NgjeyMIViYqaT1mmwjEpBVzAPFFUEDthCr0wPXlymcpk0hkYfdPepo43DtM3W6+73pDcbYIOHotrPysFrIZB0=
  template:
    metadata:
      name: pihole-admin-password
      namespace: pihole
