---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCzTPLR1yTzLkp8uQDgcLIVnianAUninV4lKxf6jVueX0VrIVKwtFbYI7Z7zreXTYdRl46encsE40ZsoPdA243hIsNUK6PcvMgYtsi1+4JOthusa6PvrNvp+MRJM/Ag+nEHscrTton8IIv7GNy3m9qZgRuDA8EWXYTwhXh9LkaBh4TFrDuKZQ3me62kbNeJuDwDJVW+0DyOQ06+Pa5SOrV3M6g95GOfKgCzGtgHtUppwRSCX5wkAtEpUCQTS6X6mxVotIv41fXHye9igsFs8Gkdh4j59+T4/WpENmeokcSRai1c5Td6CtKSW1ZofE0SG11ogVx8q9NwoWg5xDe1x5guTu0bOeqePD36l5ChgAaaK2bMUqndqkQktyfEthqqpWs2IazD39Hz+ZwKU3DHONsfNu9u3Z3SuCtyKJHNtYxuV0wxZIWaTqVbVlnkSki3IauP5ZyRSXWGXxKNf8s7pAMZTOzA2wI82gVAokjSdvg2xj4Bk+Gjnx2NSarOxlsZ4sXxiMCVPLoxKsqRSLJ2wNf80vdUy5KWzEtKteWWRZNB/xRyjcez/BqulPjgzYueDnBYI4Fr+I65cYg76JgsYvkZmBf2wecL1Oi0RE6Jxaq3UjNk/C2h0pwIsbaUZfkmBbPHW54pXd5krfzh8eIKRpe8/Wqa9HqYUlRR4FdqqhnPaMHZf0wwhJEzA86Su9qbJmzyleJTg8XGd32DlAxkHvYxMQ==
    admin-user: AgALoVz19prc5ffcvnZVoi2S8iyljTLFwhZuCX00F22fHjAchQankkBX3PQPhl3ekPpDxowOOzyZdG898SwolM+9+t5GZ5qjDGX2Lmr998bit3hKkig5EIgkMZRFvvlh4NfPT+4ycrHmacZJhUKr8RfdMJEqhjpDfAGyTdq6SkdAuFhj1GISimOWN51i6JklNazX5gW0DHc1gxvrI81s1cr0ZKg77BmHPNMN4f77oQqvlzGNz6RCbRdSVeK+cGY1bU1H0QI3H15PROfeSm1Xt43cHgDJtbbsMQnDJ2DlB+JFlIVsXUPEsKPlf8yU2YL60qr70QzsrgXXHi6ZPZ6CqIy3Olt1X/u1ATRiQh5LNFN6iG9V4rNG/Ht9/RO0kxmeSQu3cKlxlEXI+Gui0wXHVJCgSKhllmxUg7h/ubF23niDQKnM6jw+B+honVZ4OhhM3JMY0YkuU9LWEb0Egp+xIpr1kGmqvMI0lNjl1TRHyY6brHJjHLb3lIXFi6BKg+D6rllM8LTaTW0RjIlPKrs3d3iFxPxqfE2tmta8YUhONzEYsjmQZ6tNyascvYX2vAQyo/bPof8KbyHVvzTudWUG/2iaF5Y677BgeMaMr3Vc6Yb5IjrgTvIQVMcKqMSSwsIhZ6Lx7Y6CxZTcpJs0vEL7s6045ay/GM7nNNMAzsU4pvNe5TWjSew9cuGppFNHqJH/usUuTT8pHw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
