---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chromium-browserless-secret
  namespace: open-webui
spec:
  encryptedData:
    token: AgCtBgpysuuHPLB3WsVBIQyLSHwO52o5yp4NhSQk2BOCfLh31CTJyoaWdUovoDTWSH8h/jMoVNY/N20G7gh/WAqK4xPX+/7UYEbY6CQ+DErnNUCXLEla3/PnzJcLBIKom2GD01+Og8IXCs7D9GQUt3YzGlkJdJz4uKouFK2SHGp+r6qnIh4P2+sXRWxwe+sP0+HxT2rsRI5FV82iCcH5C+MeRmNC7sdJ5KP7X+E6D8WFW07MjY+RhPRTLxSCizM05MYiAbneVmU7/ZtgNpNvs7jagPhb/w2EIVxFnzfumlLQDg37HZy4/NoTpXtmC+3HR2sBZOXERBDQRw3D8fRp9zV3nc5W1kLSJtFoP+qo5LR1OnpFgKvLsS5crLBijL5okpnJ/SgY5vE1du2U11BLmyT4wlAyQ46VO0pt7tpak+WNOGKuCifJ6wvs5GLlTsZSnVuKKZNANstoHQubxbsbiREx70nVHjjJtBuPqTY11hf9zyM7P78np++Had7MnPOJNbMlGbuJIFznnd5Y3JHjOimW58zDc2sEHZ3kwFMjmSJVM9ZiZmOZE1lgbwGY6prmEVyd8DqUnEmZKEWdP6sIm9ovr1rHTX3Dr+HwmE8s3MsF9QwRneXZTIvdSKg9DTiB3pg8OTwG5xcY7KRvIsuvqSi6P52pD7LgEtOyiljzuNrsDEQPOa8gMp+hkCWkxdS3rwvTO5T1XQ9ODrzxtDyp5kzjzxCxs+upqo8osEeXtiacu4M4Zmu76RVASHXc1gQeQf0wEchjvBaztAB8Q5yzRGgN
  template:
    metadata:
      name: chromium-browserless-secret
      namespace: open-webui
