apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-scan
  namespace: update-monitoring
spec:
  schedule: "0 14 * * 6"
  timeZone: "Europe/Belgrade"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          serviceAccountName: nova
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            fsGroup: 65532
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: nova
              image: us-docker.pkg.dev/fairwinds-ops/oss/nova:v3.12.0
              imagePullPolicy: IfNotPresent
              command: ["/nova"]
              args:
                - "--format=json"
                - "find"
                - "--helm"
                - "--containers"
                - "--show-old"
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"]
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
