apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minipcs
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 41.0.0
      helm:
        releaseName: traefik
        valueFiles:
          - $values/apps/traefik/private/values.yaml
    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
