---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-admin-password
  namespace: mongodb
spec:
  encryptedData:
    password: AgBBA497f5qwwqBv/bq45ASksuXG+Ke1H2JD3HznNafWA5Sp1n/KD8xKmYGDYu8+tdBarw6/S2epCpAgPqgYQnlgLuUY9W1sztgWQQNizyw87tqttLr10DJdd72cqnJOLrD64QcJyWoF4XdbguWb92noeigZGl0wVfjeUJUmo9LhNXrHVQinPVvsx6GPw6yqh0UkIgnVVkY15/ZcqYaccBiOy/34z1mZGOg7YrENDjywk3uaGN2EFeqxXWIy8MEby5vv1ZDB7ZKeKVg3oKVjL2iVDWEyro3VBxSmhSRbHTDT4w4YWJ67rM9Apavet76t8tSuaaVSNPqj6xD4aZ1M2hb7duwDf5MZtInlcyUo9K0hG6jNHg9e8bb7AFYt0SadwP3IIa+ps4/HMnio4BlIv70PYaAYEsGLU0nBJeo1RiJZwB1fH2sfj5hv8jU8kh7mVDymbeE2wWHUyeeZp7xnKce/XaqCEZVmk/ORXYO8FOlWyo1OKqXxkZ/WNa/fbiTT96g3QBc2ny2kdobuQJbjD66AKtKH2kK7lOHK0q1XIWF3B1ClqSdlAun7Lm+WHZgOZ6UnxseaOcLlcQOB+2xOolAR1AAQbuI0aKxEmYk9wIKmuxu1OfnbKRI94tuEGf0N8h/CY+tS5IIqmz7bx7Deb8Af24lzRCgrsFXo0RH/BxMsJ4fmSQJ+KGxu80IBQA2PK3aXphU7F5NukaqHmlvV0Q==
  template:
    metadata:
      name: mongodb-admin-password
      namespace: mongodb
