---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: argocd
data:
  renovate.json: |
    {
      "extends": ["config:base"],
      "repositories": [
        "salix535/git-ops"
      ],
      "baseBranches": ["main"],
      "gitAuthor": "Renovate Bot <renovate[bot]@users.noreply.github.com>",
      "schedule": ["every weekend"],
      "automerge": false,
      "prHourlyLimit": 2,
      "prConcurrentLimit": 5,
      "rebaseWhen": "conflicted",
      "packageRules": [
        {
          "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
          "automerge": false
        }
      ]
    }
