apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  RENOVATE_PLATFORM: "github"
  RENOVATE_REPOSITORIES: "salix535/git-ops"
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_ONBOARDING: "false"
  RENOVATE_GITHUB_APP_ID: "4029949"
  RENOVATE_GITHUB_INSTALLATION_ID: "139656487"
  LOG_LEVEL: "info"
  NODE_OPTIONS: "--max-old-space-size=2048"
