apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 13 * * 0"
  timeZone: "Europe/Belgrade"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: renovate
              image: renovate/renovate:43@sha256:94ea97399b0dfba2e42b9571fc5bca6e1fbf5e72ecf6062cfe6aba5bec76b19e
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: renovate-config
              env:
                - name: RENOVATE_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: renovate-github-token
                      key: GITHUB_TOKEN
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: "1"
                  memory: 3Gi
