---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: argocd
spec:
  encryptedData:
    GITHUB_TOKEN: AgCSFaygZivYdbdLcInoUn5oyXSktUdMN5Mq1QwtPc/sO5LGmZanWTO6L9ClVxN8N+diX39OGfUfSI132GdFy5KpEtB5aZXqO+sTns6A7O14oupYp9UU1WMnmlJNEkjrEFB/YnBirwasOGL0oDnFzElefrNdwC2d5/wudkby67LKChKx0VSpmVvx04tcKZ0qQ58g/MO3SnAOGxvqRza3SVrteWJV3pNvdPIVyW62u7ygBQFih0QbZr8xXCu6mbeP1DtQhAr2YUJDU0g3QT6oGNXKONGFUP2bIsUXH2B/D9TTduXdSpIqTqsb8KP+0SSCR/2Zd/FuxOqlAu5ioloqBEuv2Me9SqoFPH3vtsoDpF8/k7wGZzRcGoLAPvmcYQv7ydcsKYs3Qkjvi6qR1xUGteGtbRzUjX8301dccknVaEDvLb8sPS5U4gvFvZ1gd/+XeE8N/9bcLOwSuJSsqxXhE0oQay2cgOKH5W22oKn8N8ZBdz0ozZ2unPtZ+7i/Y8vt8v2nsItksH+yeUmFCgCdo+yPRIYi2dELD5QLsGUL14ie1vH1lJ3NtV09qWYpura7iZyEMJFC3o/e5BcaN1Zpw1w/yfSPPMVpVkU+I09wrau/6CWInnnbFrgP8hDIDyEPmoWwZ9HfiFW+FuKOja42eBN2noHHhxSSvyvenIXjhbpyRMSLnMoL0GsbjObrtVmPKbrrQIA7+fzPJM5ZVnOQVzGL2C08oLmo
  template:
    metadata:
      name: renovate-github-token
      namespace: argocd
    type: Opaque
