---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  encryptedData:
    GITHUB_TOKEN: AgAV5eYWkyVKy3btjSrVNWzJKp4ooBWcg+TPxsIs1n9EF+JPmgYcIWyT4nyEaGfW07Rlv2vLf2qVnw7XuOpKOg/CpPSZa6HnI+oevG0/GigH/4ts6i+UFIkZW4DISIXf/JraSeZIF0KiuZsLpLD/6C0XdqA3cAKr8ebD5A2wvs2TnDJ3eSJrxxhYXZJuaM+MxB7yCqVXVYi6uTWMxNNCa0KwRdPE1u4B/viEwj3zTG0ywzgXv00lymcuy/MXSkvUD0715zV5O5on79s9BTUPU58KZpuK21/RPQmDeN5S4E9k+LpOP2yV8BKFzfkGAQyVYdgZTIq552m/DNhR0KLTgo+gjTDNllUC4t2VRGQBoVG07E8eUx9C7fNDwgHVaKndjnmxJHrj5DyZYeVAlptBE3dw3PjV5k8sDk7Gvjc17aTT+PBgk8z2PUhrNxRtPue8zHrifbstbRxIacm4/lgVP3GjHBNicM4Pc76tLXa21MKlf8L8uDrJsBHv31v/KVIsPTjrj5Y7mAM5Zsykah16RTqXoT3dmi3meIFBu0OVjv9TdcJGV9YTdnepC+mHMwdRQns8peX9+DOqCxHS83ZT3U7lX1XhTZTy2gP+qyYp6Npe7pc0Bgxe4U7MbTuY9y5Zu6WL1eoq7JooCCgx6V3VFqY97T9zWsNSkSPmbJTqzwdRNqaHrOpwLzs3SDAkqOA4MhK5EXYghiProq3m18Zc2z/J43gRRyYxVKPTYnQRvLATzFI+WPj1Exl43cH9PebCvQyodedm/X/ZdbhCcM1WHnRKjGs5tp8KfK+KNDeOMNra4W4Mqk+bGLcSzy27CJ0=
  template:
    metadata:
      name: renovate-github-token
      namespace: renovate
