apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minipcs
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 86.3.2
      helm:
        valueFiles:
          - $values/apps/monitoring/kube-prometheus-stack/values.yaml

    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      ref: values

    - repoURL: https://github.com/salix535/git-ops
      targetRevision: main
      path: apps/monitoring/kube-prometheus-stack/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
