---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: shopping-list-production
spec:
  encryptedData:
    .dockerconfigjson: AgCHrIKlClufoH5Vjprt2+6/yeHttl2zCl8vlNGyN7Wk44AkPwDVLvS8eXIaKIY7loUr9nl7enGJgu47wKsUK+4GJPgmqcUSuSHsHpAZ9LTv4U2SLqNdDe0nu4m9cqz585+GEr+1Iz+4KN0J+ccnJiB3jCwIgS+A28u+GIfnKLVEWzQp19bXDTIPY6YDSqF5Uzm2oPYddwXwWuEbPbQfSiUSXBRUJ846YkLCd/NXTNxIi6wBxSnnRPMDrx/9uQACAr3JwtAxbr5bB+59fnaAqtTlppq+koS9HpI3031L068rRS36ROjA8jfYbIOOMyzLYvYn2EG3oGBbdP5rFI+A3Jgl81lnxPKuWqcdesH9w4CWDZQeRRFb7s/K1TMSMnwFvxqNr7o9HRQqfUJKTVYAkOHsAwI0KT233FWJ2MuOK90HugHAVslOM+EYDW/H+H4OblNtFEmtPfjQccPVBb5hR1+sC+L008IRfy9HEwHQn6hSujEY93hzUDgtfzjFme8UsXuVBgpbrvqoW9lfIcrrNeegjclqfwqCvUd9O0iChL637wVN64REQYXZ6DHCSnP8ktRE5wKYOXYsgVue+S+QvdeZfeAR+Zsy3ByvqMhtZMmnuZzPw2RlkmrfFguej7js/z3E/NrkNYJTutYwjxoxhXLuOoAuZywEqjqFA7AgMlk+FYyPaYgisFtUOWcN55e3P5nnmWTMZglRv/DAodDTJr0SKafMRFm2igY/bsGSd8PYLbHjE1qaZpae3uqoRiP5SdWnJ4tkrE/TKOX9l9UgcswUT34c6VE6sh1cBWwIZGWMEgSYQdzz20HWkQhcgvoC0sk5EYAIoWQ7eub27G3VQA0exuebok6tdnD8ZRd5OY0ELfg2Vy8uZWaWUDdwzKkIeh/vi4oONlkpePrEcEndPsSnjDjwEn4lvqNW2sYGNkUIYQo=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: shopping-list-production
    type: kubernetes.io/dockerconfigjson
