---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wordpress-admin-secret
  namespace: wordpress
spec:
  encryptedData:
    wordpress-password: AgBLtekvRax0zoOr4xgnbp5QDKM3wydHQB6R1+YN3iHMj6Ecbw24i6Ej/WMJwr5N2kcCla7Qre0SoeDv3cjcR/l4xEw68PGaHdlDl8YhU0ILL6UaSQr0yR6NfRpmks8IMktuapg5S9N4cj0Z37sj3gblDNPRlXOY6BiuBKnHg4aKAeMyoO5Goh//tGOh+7t+Pis5C7fErY26mLtax58/HPNuPq8+0t8XIv7LTFhir9GwlCHDQ7vKuxPUhsn0duUTG9y6lFeGnZ642wd74cTFeveL+4FhvYKRny+f9arPjs5qrgAMI6oNXLjvTVvIr+Noemv4FmxRJqG72yjcCKp3YtCsbJg1Q3eK5D2jh1nkwfctTNHRmVu5TIxAw4LhVv5lN8AQjFeeqNXfI+gMFJqLyTnF5rk9RDoOQBBXP1VfzmA/ML6AD6rumRoy9VVorsAGPIn3k2Pfj4fT9nVmmRbvtf2b82jtMBuxNaanXGy1DeJ6mgb2XSol8sDGij6YVbVQ/qxDfrFAn8jcVRWC9a6OzW9qeIxjoMLNPyyQGWLYhs2SXVViX7wQJ3YLyzfW3k+E5VEDMVE3111Iqo/76Em49dFWMVFA7q2eFrzcMzft2p/Uv+Kf2uf9gOZJO3NpQf4zaYVmZmE+17xj8jAtVC2VZAiLcjHbtDdC+Nr469nISpO1NOuv+qsKEAdhSQjxd2Lq5jBL5U3alHZlhu236cVF8oJoizL30w==
  template:
    metadata:
      name: wordpress-admin-secret
      namespace: wordpress
